basePath: /api/v1
definitions:
  github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse:
    properties:
      error:
        example: full error text
        type: string
      message:
        example: short human-readable message
        type: string
    type: object
  internal_features_statistics_transport_http.GetStatisticsResponse:
    properties:
      tasks_average_completion_time:
        example: 1h1m30s
        type: string
      tasks_completed:
        example: 1
        type: integer
      tasks_completed_rate:
        example: 25
        type: number
      tasks_created:
        example: 4
        type: integer
    type: object
  internal_features_tasks_transport_http.CreateTaskRequest:
    properties:
      author_user_id:
        example: 1
        type: integer
      description:
        example: Do it before Friday
        maxLength: 1000
        minLength: 1
        type: string
      title:
        example: Homework
        maxLength: 100
        minLength: 1
        type: string
    required:
    - author_user_id
    - title
    type: object
  internal_features_tasks_transport_http.CreateTaskResponse:
    properties:
      author_user_id:
        example: 1
        type: integer
      completed:
        example: false
        type: boolean
      completed_at:
        example: "null"
        type: string
      created_at:
        example: "2026-01-27T11:30:00Z"
        type: string
      description:
        example: Do it before Friday
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Homework
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_tasks_transport_http.GetTaskResponse:
    properties:
      author_user_id:
        example: 1
        type: integer
      completed:
        example: false
        type: boolean
      completed_at:
        example: "null"
        type: string
      created_at:
        example: "2026-01-27T11:30:00Z"
        type: string
      description:
        example: Do it before Friday
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Homework
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_tasks_transport_http.PatchTaskRequest:
    properties:
      completed:
        type: boolean
      description:
        example: "null"
        type: string
      title:
        example: Cleaning
        type: string
    type: object
  internal_features_tasks_transport_http.PatchTaskResponse:
    properties:
      author_user_id:
        example: 1
        type: integer
      completed:
        example: false
        type: boolean
      completed_at:
        example: "null"
        type: string
      created_at:
        example: "2026-01-27T11:30:00Z"
        type: string
      description:
        example: Do it before Friday
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Homework
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_tasks_transport_http.TaskDtoResponse:
    properties:
      author_user_id:
        example: 1
        type: integer
      completed:
        example: false
        type: boolean
      completed_at:
        example: "null"
        type: string
      created_at:
        example: "2026-01-27T11:30:00Z"
        type: string
      description:
        example: Do it before Friday
        type: string
      id:
        example: 1
        type: integer
      title:
        example: Homework
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_users_transport_http.CreateUserRequest:
    properties:
      full_name:
        example: John Doe
        maxLength: 100
        minLength: 3
        type: string
      phone_number:
        example: "+48123456789"
        maxLength: 15
        minLength: 10
        type: string
    required:
    - full_name
    type: object
  internal_features_users_transport_http.CreateUserResponse:
    properties:
      full_name:
        example: John Doe
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+48123456789"
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_users_transport_http.GetUserResponse:
    properties:
      full_name:
        example: John Doe
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+48123456789"
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_users_transport_http.PatchUserRequest:
    properties:
      full_name:
        example: Jacek Sutryk
        type: string
      phone_number:
        example: "+48987654321"
        type: string
    type: object
  internal_features_users_transport_http.PatchUserResponse:
    properties:
      full_name:
        example: John Doe
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+48123456789"
        type: string
      version:
        example: 1
        type: integer
    type: object
  internal_features_users_transport_http.UserDtoResponse:
    properties:
      full_name:
        example: John Doe
        type: string
      id:
        example: 1
        type: integer
      phone_number:
        example: "+48123456789"
        type: string
      version:
        example: 1
        type: integer
    type: object
host: 127.0.0.1:5050
info:
  contact: {}
  description: Todo Application REST-API scheme
  title: Golang Todo API
  version: "1.0"
paths:
  /statistics:
    get:
      description: Get statistics about tasks with optional filtration by user ID
        and/or time range.
      parameters:
      - description: Statistics filtration by user ID
        in: query
        name: user_id
        required: true
        type: integer
      - description: Begin of statistics time range in YYYY-MM-DD format (including)
        in: query
        name: from
        required: true
        type: string
      - description: End of statistics time range in YYYY-MM-DD format (excluding)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Getting statistics details
          schema:
            $ref: '#/definitions/internal_features_statistics_transport_http.GetStatisticsResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Get statistics
      tags:
      - statistics
  /tasks:
    get:
      description: Get tasks list with optional pagination and/or filtering by author
        ID
      parameters:
      - description: Filtering by author ID
        in: query
        name: user_id
        type: integer
      - description: Limit of tasks to return
        in: query
        name: limit
        type: integer
      - description: Offset of returned tasks
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of tasks
          schema:
            items:
              $ref: '#/definitions/internal_features_tasks_transport_http.TaskDtoResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Get tasks list
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task with the provided details
      parameters:
      - description: CreateTask request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_tasks_transport_http.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created user
          schema:
            $ref: '#/definitions/internal_features_tasks_transport_http.CreateTaskResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: Author not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Create a new task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: Deletion of an existing task using the task ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Successfully deleted task
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Delete task
      tags:
      - tasks
    get:
      description: Get a task using the task ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Task details
          schema:
            $ref: '#/definitions/internal_features_tasks_transport_http.GetTaskResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Get task
      tags:
      - tasks
    patch:
      consumes:
      - application/json
      description: |-
        Change existing task
        ### Logic for patching task (Three-state logic)
        1. **field not provided**: `description` will be ignored and unchanged in database
        2. **explicitly provided value**: `"description": "Do cleaning"` will update 'description' in database
        3. **null value**: `"description": null` will remove 'description' from database (set to NULL)
        Constants: `title` and `completed` cannot be null
      parameters:
      - description: ID of task to patch
        in: path
        name: id
        required: true
        type: integer
      - description: PatchTask request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_tasks_transport_http.PatchTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Changed task details
          schema:
            $ref: '#/definitions/internal_features_tasks_transport_http.PatchTaskResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Patch task
      tags:
      - tasks
  /users:
    get:
      description: Get users list with optional pagination
      parameters:
      - description: Limit of users to return
        in: query
        name: limit
        type: integer
      - description: Offset of returned users
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/internal_features_users_transport_http.UserDtoResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Get users list
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - description: CreateUser request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_users_transport_http.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created user
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.CreateUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    delete:
      description: Deletion of an existing user using the user ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Successfully deleted user
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Delete user
      tags:
      - users
    get:
      description: Get a user using the user ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.GetUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Get user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: |-
        Change existing user
        ### Logic for patching user (Three-state logic)
        1. **field not provided**: `phone_number` will be ignored and unchanged in database
        2. **explicitly provided value**: `"phone_number": "+48987654321"` will update 'phone_number' in database
        3. **null value**: `"phone_number": null` will remove 'phone_number' from database (set to NULL)
        Constants: `full_name` cannot be null
      parameters:
      - description: ID of user to patch
        in: path
        name: id
        required: true
        type: integer
      - description: PatchUser request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_users_transport_http.PatchUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Changed user details
          schema:
            $ref: '#/definitions/internal_features_users_transport_http.PatchUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_eugeniuszglinski_golang-todoapp_internal_core_transport_http_response.ErrorResponse'
      summary: Patch user
      tags:
      - users
swagger: "2.0"
